#!/usr/bin/env bash
# ContextECF Fabric Starter — One-Command Installer
# Usage: ./install.sh [--pull-only] [--offline] [--help]
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  cat <<EOF
ContextECF Fabric Starter — Installer

Usage: ./install.sh [OPTIONS]

Options:
  --pull-only   Download images only, do not start services
  --offline     Skip image pull (use previously downloaded images)
  --help        Show this help message

Prerequisites:
  - Docker Engine 20.10+
  - Docker Compose v2+
  - 8 GB RAM minimum
  - REGISTRY_TOKEN environment variable set (provided after trial signup)

Environment:
  REGISTRY_TOKEN   Required. Registry authentication token.
  REGISTRY         Registry URL (provided with your trial credentials).
  FABRIC_VERSION   Target version (read from VERSION file if not set).
EOF
  exit 0
}

PULL_ONLY=false
OFFLINE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --pull-only) PULL_ONLY=true; shift ;;
    --offline)   OFFLINE=true; shift ;;
    --help|-h)   usage ;;
    *) echo "Unknown option: $1"; usage ;;
  esac
done

echo "=== ContextECF Fabric Starter ==="
echo ""

# Step 1: Doctor check
echo "--- Step 1: Environment checks ---"
bash "${SCRIPT_DIR}/scripts/doctor.sh"
echo ""

# Step 2: Registry authentication gate
if [ "$OFFLINE" = false ]; then
  echo "--- Step 2: Registry authentication ---"
  if [ -z "${REGISTRY_TOKEN:-}" ]; then
    echo "ERROR: REGISTRY_TOKEN is not set."
    echo ""
    echo "To obtain registry credentials, sign up for a trial at:"
    echo "  https://contextecf.com/trial"
    echo ""
    echo "Then set: export REGISTRY_TOKEN=<your-token>"
    exit 1
  fi
  echo "Registry token: present"
fi

# Step 3: Generate .env from template
echo "--- Step 3: Configuring environment ---"
ENV_FILE="${SCRIPT_DIR}/engine/.env"

if [ -f "$ENV_FILE" ]; then
  echo "Existing .env found, preserving it."
else
  VERSION="${FABRIC_VERSION:-$(cat "${SCRIPT_DIR}/VERSION" 2>/dev/null || echo 'latest')}"
  REGISTRY_URL="${REGISTRY:-REPLACE_ME}"
  PG_PASS="$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)"

  cat > "$ENV_FILE" <<ENVEOF
# Auto-generated by install.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
REGISTRY=${REGISTRY_URL}
FABRIC_VERSION=${VERSION}
POSTGRES_PASSWORD=${PG_PASS}
ENVEOF

  echo "Generated engine/.env (database password auto-created)"
fi

# Step 4: Pull images
if [ "$OFFLINE" = false ]; then
  echo "--- Step 4: Pulling images ---"
  docker compose -f "${SCRIPT_DIR}/engine/docker-compose.yml" \
    --env-file "${SCRIPT_DIR}/engine/.env" pull
  echo "Images pulled successfully."

  if [ "$PULL_ONLY" = true ]; then
    echo ""
    echo "=== Pull complete. Run './fabric up' to start services. ==="
    exit 0
  fi
fi

# Step 5: Start services
echo "--- Step 5: Starting services ---"
docker compose -f "${SCRIPT_DIR}/engine/docker-compose.yml" \
  --env-file "${SCRIPT_DIR}/engine/.env" up -d
echo ""

# Step 6: Verify
echo "--- Step 6: Verifying services ---"
bash "${SCRIPT_DIR}/scripts/verify.sh"
echo ""

echo "=== ContextECF Fabric is running ==="
echo ""
echo "  SECURITY: JWT tokens are cryptographically verified via the"
echo "  internal auth service JWKS endpoint. Do NOT set"
echo "  AUTH_ALLOW_DEV_MODE=true in any environment handling real data."
echo ""
echo "  API Gateway:    http://localhost:8080"
echo "  Admin Console:  http://localhost:3000"
echo "  PostgreSQL:     localhost:5432"
echo ""
echo "Next steps:"
echo "  ./fabric request-license    Generate trial license request"
echo "  ./fabric status             Check service status"
echo "  ./fabric down               Stop all services"
echo ""
